version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/db
    env_file:
      - db.env

  app:
    container_name: app
    build: .
    command: python3 run.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - app.env
