version: "3.8"
   
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/db
    env_file:
      - .env

  web:
    build: .
    command: python3 run.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
